    name: Publish Java Package

    on:
      release:
        types: [published] # Trigger on new releases

    jobs:
      publish:
        runs-on: ubuntu-latest
        permissions:
          contents: read
          packages: write # Required to publish packages

        steps:
        - uses: actions/checkout@v4
        - uses: actions/setup-java@v4
          with:
            distribution: 'temurin'
            java-version: '17'
        - uses: gradle/actions/setup-gradle@v3
        - name: Publish package
          run: ./gradlew publish
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}